version: 1

update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/src/RazorInteractive"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"

  - package_manager: "dotnet:nuget"
    directory: "/tests/RazorInteractive.Tests"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
