name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.101

      - name: Install dependencies
        run: dotnet restore ./src/RazorInteractive

      - name: Install dependencies for unit tests
        run: dotnet restore ./tests/RazorInteractive.Tests

      - name: Build
        run: dotnet build --nologo --configuration Release --no-restore ./src/RazorInteractive

      - name: Test
        run: dotnet test --nologo --no-restore --verbosity normal ./tests/RazorInteractive.Tests

      - name: Publish NuGet
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: ./src/RazorInteractive/RazorInteractive.csproj

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
